### ISSUE TITLE
NAT TO public ip

### ISSUE THREAD

**Issue by Dhariaj** [secureoptions/CloudShroud#1]
Is it ok and possible to NAT to a public IP address?

**Comment by secureoptions** [comment]
Yes, it can be any IP you want as long as it is not in used by your VPN peer in their network somewhere.

**Comment by Dhariaj** [comment]
Yes I got it to work using a secondary IP address.. Also thank you for taking the time to reply back to my youtube comment :)

**Comment by secureoptions** [comment]
Certainly! Anytime!
